[package]
name = "o_2_T9"
version = "0.1.0"
authors = ["coppom <manuelcoppo@grenoble-inp.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
